### ISSUE TITLE
验证码

### ISSUE THREAD

**Issue by HaHA3507** [freevolunteer/jvQuant#1]
为什么你们官网的注册  验证码无论怎么输入都是错的呢

**Comment by HaHA3507** [comment]
![image](https://github.com/freevolunteer/jvQuant/assets/87516164/da43bb75-b4bd-417b-9da7-25b3be5d1ebb)

**Comment by HaHA3507** [comment]
就这里验证码错误，怎么输入都是错的

**Comment by HaHA3507** [comment]
验证码 windows是正常的 但mac是不行的

**Comment by freevolunteer** [comment]
![ng92](https://github.com/freevolunteer/jvQuant/assets/20950039/6b3d3de6-217f-46d2-a70c-2b3d93273e94)
您好，这是技术部反馈的可能的原因:上图中可能是您的浏览器发出了相同的两次刷新验证码请求，导致您的输入匹配了第一个验证码，而服务器记录的是最后一次验证码，所以导致匹配不上。您所使用的浏览器测试部正在验证，抱歉给您带来不好的体验。如果可以，请您更换浏览器尝试一下注册，感谢您的支持和理解！

**Comment by HaHA3507** [comment]
没有试用积分的吗？
